## FEATURE ENCODING

In [16]:
import pandas as pd
import numpy as np

In [17]:
BASE_URL = "https://raw.githubusercontent.com/ProfAI/machine-learning-fondamenti/refs/heads/main/datasets/"

In [47]:
df = pd.read_csv(BASE_URL + "shirts.csv", index_col=0)
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

### Ordinal Encoding per variabili ordinali

2 modi:

In [6]:
size_mapping = {"S": 1, "M": 2, "L": 3, "XL": 4}
type(df["taglia"])

pandas.Series

In [7]:
df["taglia"] = df["taglia"].map(size_mapping)
df.head()

   taglia  colore  prezzo
0       1  bianco    4.99
1       2  bianco   19.99
2       4  bianco   12.49
3       4  bianco   14.99
4       1  bianco   14.99

In [9]:
X = df.values
type(X)

numpy.ndarray

In [10]:
size_mapping = {"S": 1, "M": 2, "L": 3, "XL": 4}

fmap = np.vectorize(lambda t:size_mapping[t])
X[:, 0] = fmap(X[:, 0])
X[: 5]

array([[1, 'bianco', 4.99],
       [2, 'bianco', 19.99],
       [4, 'bianco', 12.49],
       [4, 'bianco', 14.99],
       [1, 'bianco', 14.99]], dtype=object)

## ONE-HOT ENCODING con variabili categoriche

PANDAS

In [36]:
df = pd.get_dummies(df, columns = ["colore"])
df.head()

  taglia  prezzo  colore_bianco  colore_rosso  colore_verde
0      S    4.99           True         False         False
1      M   19.99           True         False         False
2     XL   12.49           True         False         False
3     XL   14.99           True         False         False
4      S   14.99           True         False         False

In [22]:
df = pd.get_dummies(df, columns = ["colore"], prefix="color", prefix_sep="-")
df.head()

  taglia  prezzo  color-bianco  color-rosso  color-verde
0      S    4.99          True        False        False
1      M   19.99          True        False        False
2     XL   12.49          True        False        False
3     XL   14.99          True        False        False
4      S   14.99          True        False        False

NUMPY

Utilizza un trasformatore di SciKit-Learn

In [49]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [50]:
X = df.values
X.shape

(100, 3)

In [51]:
transf = ColumnTransformer(
    [
        ("ohe", OneHotEncoder(), [1])
    ], # la funzione così composta droppa automaticamente le colonne che non sono interessate dalle trasformazioni -> usa remainder per tenerle
    remainder= "passthrough"
)

In [52]:
X = transf.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 'S', 4.99],
       [1.0, 0.0, 0.0, 'M', 19.99],
       [1.0, 0.0, 0.0, 'XL', 12.49],
       [1.0, 0.0, 0.0, 'XL', 14.99],
       [1.0, 0.0, 0.0, 'S', 14.99],
       [0.0, 0.0, 1.0, 'S', 7.99],
       [0.0, 0.0, 1.0, 'M', 4.99],
       [0.0, 0.0, 1.0, 'L', 12.49],
       [1.0, 0.0, 0.0, 'XL', 12.49],
       [0.0, 0.0, 1.0, 'M', 19.99],
       [1.0, 0.0, 0.0, 'L', 14.99],
       [1.0, 0.0, 0.0, 'XL', 19.99],
       [1.0, 0.0, 0.0, 'M', 4.99],
       [1.0, 0.0, 0.0, 'L', 7.99],
       [1.0, 0.0, 0.0, 'M', 14.99],
       [0.0, 1.0, 0.0, 'XL', 9.99],
       [0.0, 1.0, 0.0, 'S', 12.49],
       [1.0, 0.0, 0.0, 'L', 7.99],
       [1.0, 0.0, 0.0, 'XL', 4.99],
       [0.0, 0.0, 1.0, 'M', 14.99],
       [0.0, 0.0, 1.0, 'S', 14.99],
       [1.0, 0.0, 0.0, 'XL', 7.99],
       [0.0, 0.0, 1.0, 'S', 9.99],
       [1.0, 0.0, 0.0, 'XL', 14.99],
       [0.0, 1.0, 0.0, 'S', 14.99],
       [1.0, 0.0, 0.0, 'XL', 9.99],
       [0.0, 0.0, 1.0, 'M', 7.99],
       [1.0, 0.0, 0.0, 'XL', 4.99],
       [0.0, 0.0, 1.0, 'S', 14.99],
       [1.0, 0.0, 0.0, 'L', 12.49],
       [0.0, 1.0, 0.0, 'M', 9.99],
       [0.0, 0.0, 1.0, 'L', 9.99],
       [0.0, 1.0, 0.0, 'XL', 7.99],
       [1.0, 0.0, 0.0, 'M', 19.99],
       [0.0, 0.0, 1.0, 'L', 12.49],
       [1.0, 0.0, 0.0, 'L', 12.49],
       [1.0, 0.0, 0.0, 'L', 9.99],
       [1.0, 0.0, 0.0, 'XL', 14.99],
       [0.0, 0.0, 1.0, 'L', 14.99],
       [0.0, 0.0, 1.0, 'XL', 9.99],
       [1.0, 0.0, 0.0, 'M', 14.99],
       [0.0, 0.0, 1.0, 'L', 19.99],
       [0.0, 0.0, 1.0, 'XL', 7.99],
       [0.0, 0.0, 1.0, 'M', 19.99],
       [0.0, 1.0, 0.0, 'L', 19.99],
       [1.0, 0.0, 0.0, 'XL', 9.99],
       [0.0, 1.0, 0.0, 'M', 12.49],
       [1.0, 0.0, 0.0, 'S', 7.99],
       [0.0, 1.0, 0.0, 'S', 14.99],
       [0.0, 0.0, 1.0, 'S', 12.49],
       [1.0, 0.0, 0.0, 'XL', 19.99],
       [0.0, 0.0, 1.0, 'S', 14.99],
       [1.0, 0.0, 0.0, 'S', 19.99],
       [0.0, 0.0, 1.0, 'M', 9.99],
       [0.0, 0.0, 1.0, 'L', 4.99],
       [0.0, 0.0, 1.0, 'M', 12.49],
       [1.0, 0.0, 0.0, 'L', 12.49],
       [0.0, 0.0, 1.0, 'S', 7.99],
       [0.0, 0.0, 1.0, 'S', 19.99],
       [1.0, 0.0, 0.0, 'L', 9.99],
       [0.0, 1.0, 0.0, 'XL', 14.99],
       [1.0, 0.0, 0.0, 'M', 12.49],
       [1.0, 0.0, 0.0, 'XL', 14.99],
       [1.0, 0.0, 0.0, 'L', 9.99],
       [0.0, 0.0, 1.0, 'XL', 14.99],
       [1.0, 0.0, 0.0, 'L', 12.49],
       [1.0, 0.0, 0.0, 'XL', 4.99],
       [1.0, 0.0, 0.0, 'L', 14.99],
       [0.0, 0.0, 1.0, 'L', 9.99],
       [0.0, 1.0, 0.0, 'S', 14.99],
       [0.0, 1.0, 0.0, 'S', 19.99],
       [0.0, 1.0, 0.0, 'XL', 14.99],
       [1.0, 0.0, 0.0, 'S', 9.99],
       [0.0, 1.0, 0.0, 'S', 14.99],
       [1.0, 0.0, 0.0, 'L', 9.99],
       [1.0, 0.0, 0.0, 'XL', 9.99],
       [0.0, 0.0, 1.0, 'L', 19.99],
       [1.0, 0.0, 0.0, 'XL', 19.99],
       [1.0, 0.0, 0.0, 'M', 4.99],
       [1.0, 0.0, 0.0, 'M', 9.99],
       [1.0, 0.0, 0.0, 'S', 14.99],
       [1.0, 0.0, 0.0, 'L', 19.99],
       [0.0, 0.0, 1.0, 'S', 7.99],
       [0.0, 0.0, 1.0, 'XL', 9.99],
       [1.0, 0.0, 0.0, 'M', 12.49],
       [0.0, 0.0, 1.0, 'L', 4.99],
       [1.0, 0.0, 0.0, 'M', 7.99],
       [0.0, 1.0, 0.0, 'M', 14.99],
       [0.0, 1.0, 0.0, 'S', 9.99],
       [0.0, 0.0, 1.0, 'M', 4.99],
       [1.0, 0.0, 0.0, 'M', 12.49],
       [0.0, 1.0, 0.0, 'M', 14.99],
       [0.0, 0.0, 1.0, 'L', 19.99],
       [0.0, 1.0, 0.0, 'M', 7.99],
       [0.0, 0.0, 1.0, 'S', 4.99],
       [1.0, 0.0, 0.0, 'L', 9.99],
       [0.0, 0.0, 1.0, 'M', 14.99],
       [0.0, 1.0, 0.0, 'S', 12.49],
       [0.0, 1.0, 0.0, 'L', 12.49],
       [0.0, 1.0, 0.0, 'S', 19.99]], dtype=object)