## Feature Scaling

Portare tutte le feature del nostro dataset all'interno di un unico range di valori.

### Normalizzazione

In [1]:
import numpy as np
import pandas as pd

In [2]:
BASE_URL = "https://raw.githubusercontent.com/ProfAI/machine-learning-fondamenti/refs/heads/main/datasets/"

In [3]:
wine = pd.read_csv(BASE_URL + "wine.csv", usecols=[0, 1, 7])
wine.head(10)

   classe  alcol  flavonoidi
0       1  14.23        3.06
1       1  13.20        2.76
2       1  13.16        3.24
3       1  14.37        3.49
4       1  13.24        2.69
5       1  14.20        3.39
6       1  14.39        2.52
7       1  14.06        2.51
8       1  14.83        2.98
9       1  13.86        3.15

### Pandas

In [59]:
wine_norm = wine.copy()

In [51]:
features = ["alcol", "flavonoidi"]
to_norm = wine_norm[features]
wine_norm[features] = (to_norm - to_norm.min()) / (to_norm.max() - to_norm.min())
round(wine_norm.head(10), 2)

   classe  alcol  flavonoidi
0       1   0.84        0.57
1       1   0.57        0.51
2       1   0.56        0.61
3       1   0.88        0.66
4       1   0.58        0.50
5       1   0.83        0.64
6       1   0.88        0.46
7       1   0.80        0.46
8       1   1.00        0.56
9       1   0.74        0.59

In [54]:
wine_norm[features].min()

alcol         0.0
flavonoidi    0.0
dtype: float64

In [53]:
wine_norm[features].max()

alcol         1.0
flavonoidi    1.0
dtype: float64

### SciKit_Learn

In [55]:
from sklearn.preprocessing import MinMaxScaler

In [61]:
mms = MinMaxScaler()
X = wine.drop("classe", axis=1).values # la feature target non va normalizzata, quindi la rimuoviao dall'array
#axis=0 è per le righe
X_norm = mms.fit_transform(X)
print(X_norm.min(), X_norm.max())
print(X_norm[:5])

0.0 1.0
[[0.84210526 0.57383966]
 [0.57105263 0.51054852]
 [0.56052632 0.61181435]
 [0.87894737 0.66455696]
 [0.58157895 0.49578059]]

## Standardizzazione

In [10]:
wine_std = wine.copy()

In [7]:
features = ["alcol", "flavonoidi"]
to_std = wine_std[features]


wine_std[features] = (to_std - to_std.mean()) / to_std.std()
wine_std.head(10)

   classe     alcol  flavonoidi
0       1  1.514341    1.031908
1       1  0.245597    0.731565
2       1  0.196325    1.212114
3       1  1.686791    1.462399
4       1  0.294868    0.661485
5       1  1.477387    1.362285
6       1  1.711427    0.491291
7       1  1.304936    0.481280
8       1  2.253415    0.951817
9       1  1.058578    1.122011

In [8]:
# per verificare si calcola il valore medio, che deve essere 0 o tendente allo 0.

wine_std[features].mean()

alcol         3.991813e-17
flavonoidi   -3.991813e-17
dtype: float64

In [9]:
# la deviazione standard dovrebbe essere tendente all'1

wine_std[features].std()

alcol         1.0
flavonoidi    1.0
dtype: float64

### Scikit-Learn

In [12]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X = wine.drop("classe",axis=1).values
X_std = ss.fit_transform(X)
X_std[:5]

array([[1.51861254, 1.03481896],
       [0.24628963, 0.73362894],
       [0.19687903, 1.21553297],
       [1.69154964, 1.46652465],
       [0.29570023, 0.66335127]])

In [13]:
X_std.mean()

np.float64(-6.187310339484019e-16)

In [14]:
X_std.std()

np.float64(1.0)

i numeri che otteniamo sono leggermente diversi. Questo perchè scikitlearn utilizza numpy per calcolare la deviazione standard. numpy e pandas la calcolano in modi diversi. Se vogliamo uniformità anche con pandas:

In [16]:
wines_std = wine.copy()

features = ["alcol","flavonoidi"]
to_std = wine_std[features]
wine_std[features] = (to_std - to_std.mean())/to_std.std(ddof=0) #ddof=0 per replicare i risultati di sklearn. Aggiugiamo questo parametro e lo settiamo a 0. Normalmente è 1.
wine_std[:5]

   classe     alcol  flavonoidi
0       1  1.518613    1.034819
1       1  0.246290    0.733629
2       1  0.196879    1.215533
3       1  1.691550    1.466525
4       1  0.295700    0.663351

La differenza è questa:

Deviazione standard della <b> popolazione </b>: usa tutti i dati disponibili della popolazione
Deviazione standard del campione: usa solo un sottoinsieme dei dati e corregge il calcolo per stimare meglio la variabilità della popolazione
La formula cambia nel denominatore:

Popolazione: si divide per N
Campione: si divide per N - 1
Dove N è il numero di osservazioni.

Perché compare N - 1 nel campione?

Perché quando usi un <b> campione</b>, stai cercando di stimare la variabilità dell’intera popolazione partendo da pochi dati. Dividere per N - 1 invece che per N introduce una piccola correzione che rende la stima meno “ottimista” e più accurata in media.

Esempio pratico: supponi di avere i valori [2, 4, 6].

Calcoli la media: 
μ = 2 + 4 + 63 = 4
μ= 32+4+6 = 4

Calcoli gli scarti dalla media:

2 - 4 = -2
4 - 4 = 0
6 - 4 = 2
Sommi i quadrati: 
4 + 0 + 4 = 8
4+0+4=8

Varianza e deviazione standard:

Popolazione: varianza = 8 / 3
Campione: varianza = 8 / 2
Quindi la deviazione standard del campione risulta più grande.

Nel video, la differenza tra Pandas e scikit-learn nasce proprio da questo:

Pandas di default usa la deviazione standard campionaria
NumPy, e quindi spesso anche scikit-learn, usa quella della popolazione